
import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.magazine': 'Magazine',
    'nav.companies': 'For Companies',
    'nav.contact': 'Contact',
    'nav.get_featured': 'Get Featured',
    'nav.directory': 'Directory',
    'hero.label': 'Live from Rhein-Neckar',
    'hero.title': 'The Leading SHK Industry Magazine.',
    'hero.subtitle': 'Trusted industry coverage, insights, and success stories for sanitary, heating, and climate professionals in the Rhein-Neckar region.',
    'hero.read_latest': 'Read Latest',
    'hero.submit_story': 'Submit a Story',
    'section.top_story': 'Top Story',
    'section.latest_news': 'Latest Industry News',
    'section.trust_title': 'Deeply Rooted in Rhein-Neckar',
    'section.trust_text': 'We don\'t just report on the industry; we are part of the local ecosystem. Connecting businesses in Mannheim, Heidelberg, Ludwigshafen, and beyond.',
    'section.explore_categories': 'Explore Topics',
    'newsletter.title': 'Stay Informed. No Spam.',
    'newsletter.text': 'Get the weekly digest of the most important SHK news in Rhein-Neckar. Used by over 2,000 local professionals.',
    'newsletter.placeholder': 'Your work email...',
    'newsletter.button': 'Subscribe',
    'newsletter.disclaimer': 'Unsubscribe at any time.',
    'footer.about': 'The independent voice for the Sanitary, Heating, and Climate industry in the metropolitan region.',
    'footer.rights': 'All rights reserved.',
    'footer.staff_login': 'Staff Login',
    'article.read_story': 'Read Story',
    'article.watch_video': 'Watch Video',
    'article.back': 'Back to Magazine',
    'article.read_time': 'min read',
    'article.share': 'Share',
    'article.enjoyed': 'Enjoyed this story?',
    'article.subscribe_promo': 'Join 2,000+ local professionals receiving our weekly SHK industry briefing.',
    'search.placeholder': 'Search articles...',
    'search.no_results': 'No articles found matching your search.',
    'btn.show_more': 'Show More',
    'btn.load_more': 'Load More Articles',
    'btn.view_category': 'View Category',
    'directory.title': 'Business Directory',
    'directory.subtitle': 'Find trusted SHK partners in the Rhein-Neckar region.',
    'directory.search_placeholder': 'Search by name or city...',
    'directory.filter_all': 'All',
    
    // Category Translations (Keys match the German data strings)
    'cat.Branchen-News': 'Industry News',
    'cat.Betriebs-Features': 'Company Features',
    'cat.Personal & Karriere': 'HR & Careers',
    'cat.Technologie': 'Technology',
    'cat.Energie & Nachhaltigkeit': 'Energy & Sustainability',
    'cat.Regional': 'Regional',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.magazine': 'Magazin',
    'nav.companies': 'Für Unternehmen',
    'nav.contact': 'Kontakt',
    'nav.get_featured': 'Artikel Einreichen',
    'nav.directory': 'Branchenbuch',
    'hero.label': 'Live aus Rhein-Neckar',
    'hero.title': 'Das führende SHK-Branchenmagazin.',
    'hero.subtitle': 'Verlässliche Berichterstattung, Einblicke und Erfolgsgeschichten für Sanitär-, Heizungs- und Klimaprofis in der Metropolregion Rhein-Neckar.',
    'hero.read_latest': 'Aktuelles lesen',
    'hero.submit_story': 'Story einreichen',
    'section.top_story': 'Top Story',
    'section.latest_news': 'Neueste Branchennachrichten',
    'section.trust_title': 'Tief verwurzelt in Rhein-Neckar',
    'section.trust_text': 'Wir berichten nicht nur über die Branche; wir sind Teil des lokalen Ökosystems. Wir verbinden Unternehmen in Mannheim, Heidelberg, Ludwigshafen und darüber hinaus.',
    'section.explore_categories': 'Themen Entdecken',
    'newsletter.title': 'Informiert bleiben. Kein Spam.',
    'newsletter.text': 'Erhalten Sie die wöchentliche Zusammenfassung der wichtigsten SHK-Nachrichten. Gelesen von über 2.000 lokalen Profis.',
    'newsletter.placeholder': 'Ihre geschäftliche E-Mail...',
    'newsletter.button': 'Abonnieren',
    'newsletter.disclaimer': 'Jederzeit abbestellbar.',
    'footer.about': 'Die unabhängige Stimme für die Sanitär-, Heizungs- und Klimabranche in der Metropolregion.',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.staff_login': 'Mitarbeiter Login',
    'article.read_story': 'Artikel lesen',
    'article.watch_video': 'Video ansehen',
    'article.back': 'Zurück zum Magazin',
    'article.read_time': 'Min Lesezeit',
    'article.share': 'Teilen',
    'article.enjoyed': 'Hat Ihnen der Artikel gefallen?',
    'article.subscribe_promo': 'Schließen Sie sich 2.000+ lokalen Profis an und erhalten Sie unser wöchentliches Briefing.',
    'search.placeholder': 'Artikel suchen...',
    'search.no_results': 'Keine Artikel gefunden.',
    'btn.show_more': 'Mehr Anzeigen',
    'btn.load_more': 'Weitere Artikel laden',
    'btn.view_category': 'Kategorie ansehen',
    'directory.title': 'Branchenbuch',
    'directory.subtitle': 'Finden Sie verlässliche SHK-Partner in der Rhein-Neckar-Region.',
    'directory.search_placeholder': 'Suche nach Name oder Ort...',
    'directory.filter_all': 'Alle',

    // Category Translations
    'cat.Branchen-News': 'Branchen-News',
    'cat.Betriebs-Features': 'Betriebs-Features',
    'cat.Personal & Karriere': 'Personal & Karriere',
    'cat.Technologie': 'Technologie',
    'cat.Energie & Nachhaltigkeit': 'Energie & Nachhaltigkeit',
    'cat.Regional': 'Regional',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.magazine': 'Magazine',
    'nav.companies': 'Pour les entreprises',
    'nav.contact': 'Contact',
    'nav.get_featured': 'Être en vedette',
    'nav.directory': 'Annuaire',
    'hero.label': 'En direct de Rhein-Neckar',
    'hero.title': 'Le premier magazine de l\'industrie SHK.',
    'hero.subtitle': 'Couverture fiable de l\'industrie pour les professionnels du sanitaire, du chauffage et du climat dans la région de Rhein-Neckar.',
    'hero.read_latest': 'Lire les dernières nouvelles',
    'hero.submit_story': 'Soumettre une histoire',
    'section.top_story': 'À la une',
    'section.latest_news': 'Dernières nouvelles de l\'industrie',
    'section.trust_title': 'Profondément enraciné',
    'section.trust_text': 'Nous connectons les entreprises à Mannheim, Heidelberg, Ludwigshafen et au-delà.',
    'section.explore_categories': 'Explorer les sujets',
    'newsletter.title': 'Restez informé.',
    'newsletter.text': 'Recevez le résumé hebdomadaire des nouvelles SHK les plus importantes.',
    'newsletter.placeholder': 'Votre email professionnel...',
    'newsletter.button': 'S\'abonner',
    'newsletter.disclaimer': 'Se désabonner à tout moment.',
    'footer.about': 'La voix indépendante de l\'industrie SHK dans la région métropolitaine.',
    'footer.rights': 'Tous droits réservés.',
    'footer.staff_login': 'Connexion personnel',
    'article.read_story': 'Lire l\'histoire',
    'article.watch_video': 'Regarder la vidéo',
    'article.back': 'Retour au magazine',
    'article.read_time': 'min de lecture',
    'article.share': 'Partager',
    'article.enjoyed': 'Vous avez aimé cette histoire ?',
    'article.subscribe_promo': 'Rejoignez 2 000+ professionnels locaux.',
    'search.placeholder': 'Rechercher des articles...',
    'search.no_results': 'Aucun article trouvé.',
    'btn.show_more': 'Montrer plus',
    'btn.load_more': 'Charger plus d\'articles',
    'btn.view_category': 'Voir la catégorie',
    'directory.title': 'Annuaire des entreprises',
    'directory.subtitle': 'Trouvez des partenaires SHK de confiance dans la région de Rhein-Neckar.',
    'directory.search_placeholder': 'Rechercher par nom ou ville...',
    'directory.filter_all': 'Tous',

    // Category Translations
    'cat.Branchen-News': 'Actualités de l\'industrie',
    'cat.Betriebs-Features': 'Fonctionnalités de l\'entreprise',
    'cat.Personal & Karriere': 'RH et carrières',
    'cat.Technologie': 'Technologie',
    'cat.Energie & Nachhaltigkeit': 'Énergie et durabilité',
    'cat.Regional': 'Régional',
  },
  it: {
    'nav.home': 'Home',
    'nav.magazine': 'Rivista',
    'nav.companies': 'Per le aziende',
    'nav.contact': 'Contatto',
    'nav.get_featured': 'Mettiti in luce',
    'nav.directory': 'Elenco',
    'hero.label': 'In diretta da Rhein-Neckar',
    'hero.title': 'La rivista leader del settore SHK.',
    'hero.subtitle': 'Copertura affidabile del settore per i professionisti di sanitari, riscaldamento e clima nella regione Rhein-Neckar.',
    'hero.read_latest': 'Leggi le ultime',
    'hero.submit_story': 'Invia una storia',
    'section.top_story': 'Storia principale',
    'section.latest_news': 'Ultime notizie del settore',
    'section.trust_title': 'Profondamente radicato',
    'section.trust_text': 'Colleghiamo le aziende a Mannheim, Heidelberg, Ludwigshafen e oltre.',
    'section.explore_categories': 'Esplora argomenti',
    'newsletter.title': 'Rimani informato.',
    'newsletter.text': 'Ricevi il riepilogo settimanale delle notizie SHK più importanti.',
    'newsletter.placeholder': 'La tua email aziendale...',
    'newsletter.button': 'Iscriviti',
    'newsletter.disclaimer': 'Annulla iscrizione in qualsiasi momento.',
    'footer.about': 'La voce indipendente per il settore SHK nella regione metropolitana.',
    'footer.rights': 'Tutti i diritti riservati.',
    'footer.staff_login': 'Login personale',
    'article.read_story': 'Leggi storia',
    'article.watch_video': 'Guarda video',
    'article.back': 'Torna alla rivista',
    'article.read_time': 'min di lettura',
    'article.share': 'Condividi',
    'article.enjoyed': 'Ti è piaciuta questa storia?',
    'article.subscribe_promo': 'Unisciti a 2.000+ professionisti locali.',
    'search.placeholder': 'Cerca articoli...',
    'search.no_results': 'Nessun articolo trovato.',
    'btn.show_more': 'Mostra di più',
    'btn.load_more': 'Carica altri articoli',
    'btn.view_category': 'Vedi categoria',
    'directory.title': 'Elenco delle aziende',
    'directory.subtitle': 'Trova partner SHK affidabili nella regione Rhein-Neckar.',
    'directory.search_placeholder': 'Cerca per nome o città...',
    'directory.filter_all': 'Tutti',

    // Category Translations
    'cat.Branchen-News': 'Notizie del settore',
    'cat.Betriebs-Features': 'Caratteristiche aziendali',
    'cat.Personal & Karriere': 'Risorse umane e carriera',
    'cat.Technologie': 'Tecnologia',
    'cat.Energie & Nachhaltigkeit': 'Energia e sostenibilità',
    'cat.Regional': 'Regionale',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.magazine': 'Revista',
    'nav.companies': 'Para empresas',
    'nav.contact': 'Contacto',
    'nav.get_featured': 'Destacarse',
    'nav.directory': 'Directorio',
    'hero.label': 'En vivo desde Rhein-Neckar',
    'hero.title': 'La revista líder de la industria SHK.',
    'hero.subtitle': 'Cobertura confiable de la industria para profesionales de sanitarios, calefacción y clima en la región de Rhein-Neckar.',
    'hero.read_latest': 'Leer lo último',
    'hero.submit_story': 'Enviar historia',
    'section.top_story': 'Historia principal',
    'section.latest_news': 'Últimas noticias de la industria',
    'section.trust_title': 'Profundamente arraigado',
    'section.trust_text': 'Conectamos empresas en Mannheim, Heidelberg, Ludwigshafen y más allá.',
    'section.explore_categories': 'Explorar temas',
    'newsletter.title': 'Manténgase informado.',
    'newsletter.text': 'Reciba el resumen semanal de las noticias SHK más importantes.',
    'newsletter.placeholder': 'Su correo corporativo...',
    'newsletter.button': 'Suscribirse',
    'newsletter.disclaimer': 'Darse de baja en cualquier momento.',
    'footer.about': 'La voz independiente de la industria SHK en la región metropolitana.',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.staff_login': 'Acceso personal',
    'article.read_story': 'Leer historia',
    'article.watch_video': 'Ver video',
    'article.back': 'Volver a la revista',
    'article.read_time': 'min de lectura',
    'article.share': 'Compartir',
    'article.enjoyed': '¿Le gustó esta historia?',
    'article.subscribe_promo': 'Únase a 2,000+ profesionales locales.',
    'search.placeholder': 'Buscar artículos...',
    'search.no_results': 'No se encontraron artículos.',
    'btn.show_more': 'Mostrar más',
    'btn.load_more': 'Cargar más artículos',
    'btn.view_category': 'Ver categoría',
    'directory.title': 'Directorio de empresas',
    'directory.subtitle': 'Encuentre socios SHK de confianza en la región de Rhein-Neckar.',
    'directory.search_placeholder': 'Buscar por nombre o ciudad...',
    'directory.filter_all': 'Todos',

    // Category Translations
    'cat.Branchen-News': 'Noticias de la industria',
    'cat.Betriebs-Features': 'Características de la empresa',
    'cat.Personal & Karriere': 'Recursos humanos y carreras',
    'cat.Technologie': 'Tecnología',
    'cat.Energie & Nachhaltigkeit': 'Energía y sostenibilidad',
    'cat.Regional': 'Regional',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string): string => {
    // If key starts with 'cat.' check specific category translation, else generic
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
